using SpatialViewer.Core;

namespace SpatialViewer.Core.Tests;

public sealed class MathAndBoundsTests
{
    [Fact] public void TransformComposesAndInverts() { var transform = Transform2D.Scale(2, 3).Then(Transform2D.Rotation(Math.PI / 2)).Then(Transform2D.Translation(10, -5)); var point = new Point2D(4, 2); var result = transform.Apply(point); Assert.True(transform.TryInvert(out var inverse)); var roundTrip = inverse.Apply(result); Assert.Equal(point.X, roundTrip.X, 10); Assert.Equal(point.Y, roundTrip.Y, 10); }
    [Fact] public void BoundsUnionAndTransforms() { var left = new BoundingBox2D(-5, -2, 0, 4); var right = new BoundingBox2D(3, -7, 9, 2); var union = left.Union(right); Assert.Equal(new BoundingBox2D(-5, -7, 9, 4), union); Assert.Equal(new BoundingBox2D(5, -2, 10, 4), left.Transform(Transform2D.Translation(10, 0))); }
    [Fact] public void EmptyBoundsAreNeutralForUnion() => Assert.Equal(new BoundingBox2D(1, 2, 3, 4), BoundingBox2D.Empty.Union(new(1, 2, 3, 4)));
}

public sealed class SceneAndViewportTests
{
    [Fact] public void SceneUsesLayerVisibilityAndStableIds() { var document = SyntheticScenes.BasicPrimitives(); var initial = document.Scene.GetItems().Count(); var id = document.Scene.GetItems().First().Id; document.Layers[0].IsVisible = false; Assert.True(document.Scene.GetItems().Count() < initial); Assert.DoesNotContain(document.Scene.GetItems(), item => item.Id == id); document.Layers[0].IsVisible = true; Assert.Contains(document.Scene.GetItems(), item => item.Id == id); }
    [Fact] public void SceneCachesFlattenedTransformsWithoutBreakingVisibility() { var layer = new Layer("cached", "Cached"); var child = new SceneNode(ObjectId.New(), new LineGeometry(new(0, 0), new(2, 0)), Transform2D.Translation(3, 4)); var root = new SceneNode(ObjectId.New(), transform: Transform2D.Scale(2, 2), children: new[] { child }); var scene = new Scene2D(new[] { new SceneLayer(layer, new[] { root }) }); var first = Assert.Single(scene.GetItems()); var second = Assert.Single(scene.GetItems()); Assert.Equal(first, second); Assert.Equal(new BoundingBox2D(6, 8, 10, 8), first.Bounds); layer.IsVisible = false; Assert.Empty(scene.GetItems()); Assert.Equal(first.Bounds, scene.GetBounds(false)); }
    [Fact] public void CameraRoundTripsLargeWorldCoordinates() { var camera = new Camera2D(new(500000, 3400000), 4.5); var size = new Size2D(1920, 1080); var world = new Point2D(500123.456789, 3400456.123456); var result = camera.ScreenToWorld(camera.WorldToScreen(world, size), size); Assert.Equal(world.X, result.X, 9); Assert.Equal(world.Y, result.Y, 9); }
    [Fact] public void CameraZoomAroundCursorKeepsAnchor() { var camera = new Camera2D(new(10, 20), 2); var size = new Size2D(800, 600); var cursor = new Point2D(230, 120); var before = camera.ScreenToWorld(cursor, size); camera.ZoomAt(3, cursor, size); var after = camera.ScreenToWorld(cursor, size); Assert.Equal(before.X, after.X, 10); Assert.Equal(before.Y, after.Y, 10); }
    [Fact] public void CameraFitsBounds() { var camera = new Camera2D(Point2D.Origin); var bounds = new BoundingBox2D(500000, 3400000, 501000, 3400500); camera.Fit(bounds, new(1000, 600)); Assert.Equal(bounds.Center, camera.Target); Assert.InRange(camera.Zoom, .8, .85); }
    [Fact] public void HitTestFiltersHiddenLayersAndFindsCircle() { var document = SyntheticScenes.BasicPrimitives(); var circle = document.Scene.GetItems().First(item => item.Geometry is CircleGeometry geometry && geometry.Center == new Point2D(160, 40)); Assert.Equal(circle.Id, HitTesting.HitTest(document.Scene, new(188, 40), 1)?.Id); circle.Layer.IsVisible = false; Assert.Null(HitTesting.HitTest(document.Scene, new(188, 40), 1)); }
    [Fact] public void HitTestRejectsCirclePortionOutsideArcSweep() { var layer = new Layer("arc", "Arc"); var node = new SceneNode(ObjectId.New(), new ArcGeometry(Point2D.Origin, 10, 0, Math.PI * 1.5)); var scene = new Scene2D(new[] { new SceneLayer(layer, new[] { node }) }); Assert.NotNull(HitTesting.HitTest(scene, new(0, 10), .1)); Assert.Null(HitTesting.HitTest(scene, new(7.0710678118654755, -7.0710678118654755), .1)); }
    [Fact] public void HitTestKeepsWorldToleranceForCompressedTransforms() { var layer = new Layer("scaled", "Scaled"); var node = new SceneNode(ObjectId.New(), new LineGeometry(new(0, 0), new(100, 0)), Transform2D.Scale(.1, .1)); var scene = new Scene2D(new[] { new SceneLayer(layer, new[] { node }) }); Assert.NotNull(HitTesting.HitTest(scene, new(5, .75), 1)); Assert.Null(HitTesting.HitTest(scene, new(5, 1.25), 1)); }
    [Fact] public void HitTestSupportsDegenerateEllipses() { var layer = new Layer("ellipse", "Ellipse"); var vertical = new SceneNode(ObjectId.New(), new EllipseGeometry(new(0, 0), 0, 5)); var point = new SceneNode(ObjectId.New(), new EllipseGeometry(new(20, 20), 0, 0)); var scene = new Scene2D(new[] { new SceneLayer(layer, new[] { vertical, point }) }); Assert.NotNull(HitTesting.HitTest(scene, new(0, 2), .1)); Assert.NotNull(HitTesting.HitTest(scene, new(20, 20), .1)); }
    [Fact] public void HitTestSupportsEveryStageOneGeometry() { var layer = new Layer("test", "Test"); var nodes = new[] { new SceneNode(ObjectId.New(), new PointGeometry(new(0, 0))), new SceneNode(ObjectId.New(), new LineGeometry(new(10, 0), new(20, 0))), new SceneNode(ObjectId.New(), new PolylineGeometry(new[] { new Point2D(30, 0), new(40, 0) })), new SceneNode(ObjectId.New(), new PolygonGeometry(new[] { new Point2D(50, 0), new(60, 0), new(55, 10) })), new SceneNode(ObjectId.New(), new RectangleGeometry(new(70, 0, 80, 10))), new SceneNode(ObjectId.New(), new CircleGeometry(new(95, 5), 5)), new SceneNode(ObjectId.New(), new ArcGeometry(new(110, 5), 5, 0, Math.PI)), new SceneNode(ObjectId.New(), new EllipseGeometry(new(125, 5), 5, 3)), new SceneNode(ObjectId.New(), new PathGeometry(new[] { new Point2D(135, 0), new(145, 0) })), new SceneNode(ObjectId.New(), new TextGeometry(new(150, 10), "T", 10)), new SceneNode(ObjectId.New(), new ImageGeometry(new(165, 0), new(10, 10), "placeholder")) }; var scene = new Scene2D(new[] { new SceneLayer(layer, nodes) }); foreach (var point in new[] { new Point2D(0, 0), new(15, 0), new(35, 0), new(55, 5), new(75, 5), new(100, 5), new(110, 10), new(130, 5), new(140, 0), new(153, 5), new(170, 5) }) Assert.NotNull(HitTesting.HitTest(scene, point, 1)); }
}
